### ISSUE TITLE
脑图提取密码是什么啊？貌似按你的安装完不好使呢 。。。打不开。。。怎么破。。。

### ISSUE THREAD

**Issue by zf329398320** [wzdxy/vue2-in-yii2#1]

**Comment by wzdxy** [comment]
Sorry, **Password: Q1Wk**
Cannot open? Which url did you open ?
Pull my new commit and try this:
`blog URL:f.localhost`
`admin URL:b.localhost/site/index#/personalcenter`
Don't forget the config of apache.
